name: Develop in a branch

on: [pull_request, workflow_dispatch]

jobs:
  job1:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - run: |
        echo "${{ github.event.pull_request.title }}"
    - run: |
        echo "Przepływ pracy wyzwolony w odgałęzieniu '${{ github.ref }}'."
        echo "Przepływ pracy wyzwolony przez zdarzenie '${{ github.event_name }}'."
        echo "Przepływ pracy wyzwolony przez aktora '${{ github.actor }}''."
    - run: |
        echo "::debug::To jest komunikat debugowania."
        echo "::notice::To jest komunikat powiadomienia."
        echo "::warning::To jest komunikat ostrzegawczy."
        echo "::error::To jest komunikat o błędzie."
    - uses: actions/checkout@v4.1.0
    - uses: devops-actions/actionlint@v0.1.12
