
name: dotnet-webapp-build

on:
  push:
    paths:
      - ".github/workflows/dotnet-webapp-build.yml"
      - "dotnetwebapp/MyWebApp/**"
  workflow_dispatch:

jobs:
  build:
    name: build-dotnet-webapp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: dotnet --list-runtimes
      - run: dotnet --list-sdks
      - run: dotnet build
        working-directory: ./dotnetwebapp/MyWebApp
      - run: dotnet test
        working-directory: ./dotnetwebapp/MyWebApp
