name: Auto-describe

on: 
  issue_comment:
    types: [created]

jobs:
  label:
    permissions: 
      issues: write
    runs-on: ubuntu-latest
    steps:
    - name: Change label to "auto-assignet"
      if: startsWith(github.event.comment.body, '/assignet')
      run: |
        gh issue edit "$ISSUE" --add-label "auto-assignet" --repo "$REPO"
      env:
        ISSUE: ${{ github.event.issue.number }}
        REPO: ${{ github.event.repository.full_name }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test_job:
    runs-on: ubuntu-latest
    steps:
    - name: Test echo
      run: |
        echo "TATA"

  test_job2:
    runs-on: ubuntu-latest
    needs: label
    steps:
    - name: Test echo
      run: |
        echo "MAMA"

  test_job3:
    runs-on: ubuntu-latest
    steps:
    - name: Test echo
      run: |
        echo "MAMA"
